import { customType, timestamp, uuid } from "drizzle-orm/pg-core";

/** UUID primary key, generated by Postgres. */
export const id = () => uuid("id").primaryKey().defaultRandom();

/**
 * created_at / updated_at for every table. updated_at is set by the `set_updated_at` trigger
 * (migration 0003), so it changes on every UPDATE, including raw SQL and admin edits.
 */
export const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
};

/** Longitude/latitude in WGS 84 (SRID 4326). x = longitude, y = latitude. */
export type Point = { x: number; y: number };

/** Polygon as GeoJSON-style rings of [longitude, latitude]; the first ring is the outer boundary. */
export type Polygon = [number, number][][];

const SRID = 4326;

// PostGIS lives in the `extensions` schema (migration 0000). The type is left unqualified because drizzle-kit
// quotes qualified custom types; it resolves through search_path, which migration 0000 sets to include `extensions`.
export const point = customType<{ data: Point; driverData: string }>({
  dataType() {
    return `geometry(Point, ${SRID})`;
  },
  toDriver(value) {
    return `SRID=${SRID};POINT(${value.x} ${value.y})`;
  },
  fromDriver(value) {
    const geometry = parseEwkb(value);
    if (geometry.type !== "Point") throw new Error(`Expected Point, got ${geometry.type}`);
    return geometry.point;
  },
});

export const polygon = customType<{ data: Polygon; driverData: string }>({
  dataType() {
    return `geometry(Polygon, ${SRID})`;
  },
  toDriver(value) {
    const rings = value.map((ring) => `(${ring.map(([x, y]) => `${x} ${y}`).join(", ")})`);
    return `SRID=${SRID};POLYGON(${rings.join(", ")})`;
  },
  fromDriver(value) {
    const geometry = parseEwkb(value);
    if (geometry.type !== "Polygon") throw new Error(`Expected Polygon, got ${geometry.type}`);
    return geometry.rings;
  },
});

type ParsedGeometry = { type: "Point"; point: Point } | { type: "Polygon"; rings: Polygon };

/** Parses the hex EWKB that Postgres returns for geometry columns (Point and Polygon only). */
export function parseEwkb(hex: string): ParsedGeometry {
  const view = new DataView(Uint8Array.from(hex.match(/../g) ?? [], (b) => parseInt(b, 16)).buffer);
  const littleEndian = view.getUint8(0) === 1;
  let offset = 1;
  const readUint32 = () => {
    const v = view.getUint32(offset, littleEndian);
    offset += 4;
    return v;
  };
  const readDouble = () => {
    const v = view.getFloat64(offset, littleEndian);
    offset += 8;
    return v;
  };

  const typeWithFlags = readUint32();
  if (typeWithFlags & 0x20000000) readUint32(); // skip SRID
  const type = typeWithFlags & 0xff;

  if (type === 1) return { type: "Point", point: { x: readDouble(), y: readDouble() } };
  if (type === 3) {
    const rings: Polygon = [];
    const ringCount = readUint32();
    for (let r = 0; r < ringCount; r++) {
      const ring: [number, number][] = [];
      const pointCount = readUint32();
      for (let p = 0; p < pointCount; p++) ring.push([readDouble(), readDouble()]);
      rings.push(ring);
    }
    return { type: "Polygon", rings };
  }
  throw new Error(`Unsupported geometry type ${type}`);
}
